# Generated by Django 3.1.5 on 2021-01-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_auto_20210121_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='username',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date',
            field=models.DateTimeField(default='2021-01-25'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-01-25'),
        ),
    ]
